name: تشغيل البوت

on:
  schedule:
    # يعمل كل 15 دقيقة
    - cron: '*/15 * * * *'
  # هذا السطر يسمح لك بتشغيله يدوياً للتجربة متى ما بغيت
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: سحب الكود (Checkout)
        uses: actions/checkout@v3

      - name: إعداد بايثون (Setup Python)
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: تنصيب المكتبات (Install Requirements)
        run: |
          pip install -r requirements.txt

      - name: تشغيل الكود (Run Main Script)
        env:
          # هنا نربط المفتاح السري بالكود
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python main.py
