name: ØªØ´ØºÙŠÙ„ Ø¨ÙˆØª Ø·Ø±ÙˆØ¯

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install libraries
        run: pip install selenium webdriver-manager firebase-admin

      - name: Run Python Script
        env:
          TOROD_EMAIL: ${{ secrets.TOROD_EMAIL }}
          TOROD_PASSWORD: ${{ secrets.TOROD_PASSWORD }}
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python main.py

      # ğŸ‘‡ğŸ‘‡ğŸ‘‡ Ù‡Ø°Ù‡ Ø§Ù„Ø®Ø·ÙˆØ© Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø© Ù„Ø±ÙØ¹ Ø§Ù„ØµÙˆØ± ğŸ‘‡ğŸ‘‡ğŸ‘‡
      - name: Upload Screenshots
        if: always() # Ø§Ø±ÙØ¹ Ø§Ù„ØµÙˆØ± Ø­ØªÙ‰ Ù„Ùˆ ÙØ´Ù„ Ø§Ù„Ø¨ÙˆØª
        uses: actions/upload-artifact@v4
        with:
          name: bot-screenshots
          path: "*.png"
